// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3_eCWI-cCKEMZ98f-vDzqeVoz-2Kubk',
    appId: '1:254035602639:web:4befb8ea23afa57b359bba',
    messagingSenderId: '254035602639',
    projectId: 'online-class-fde14',
    authDomain: 'online-class-fde14.firebaseapp.com',
    storageBucket: 'online-class-fde14.firebasestorage.app',
    measurementId: 'G-TWP87SYFYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKc5yRW4K8Gk0TCaEXFHn_gBJmQeXz8v0',
    appId: '1:254035602639:android:24b12e663f597901359bba',
    messagingSenderId: '254035602639',
    projectId: 'online-class-fde14',
    storageBucket: 'online-class-fde14.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3_eCWI-cCKEMZ98f-vDzqeVoz-2Kubk',
    appId: '1:254035602639:web:9e0947dac17aca74359bba',
    messagingSenderId: '254035602639',
    projectId: 'online-class-fde14',
    authDomain: 'online-class-fde14.firebaseapp.com',
    storageBucket: 'online-class-fde14.firebasestorage.app',
    measurementId: 'G-EMNRYYH1E1',
  );
}

// 